"""empty message

Revision ID: 053cc8402cde
Revises: cb688fa9f4ef
Create Date: 2021-04-19 10:54:36.415178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053cc8402cde'
down_revision = 'cb688fa9f4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_history', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'position')
    op.drop_column('block_history', 'status')
    # ### end Alembic commands ###
