"""empty message

Revision ID: 32b3fceaa7d4
Revises: 7f355c0281d1
Create Date: 2021-04-20 16:08:44.409559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b3fceaa7d4'
down_revision = '7f355c0281d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('remove', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'remove')
    # ### end Alembic commands ###
