"""empty message

Revision ID: 3316e56ae35e
Revises: 724569e56314
Create Date: 2021-04-23 13:49:12.855710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3316e56ae35e'
down_revision = '724569e56314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('filter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_status', 'filter')
    # ### end Alembic commands ###
