"""empty message

Revision ID: 5ac8a290ef89
Revises: 32b3fceaa7d4
Create Date: 2021-04-21 09:15:20.024008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac8a290ef89'
down_revision = '32b3fceaa7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calls_id_clients_contact_fkey', 'calls', type_='foreignkey')
    op.drop_constraint('calls_id_clients_fkey', 'calls', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('calls_id_clients_fkey', 'calls', 'clients', ['id_clients'], ['id'])
    op.create_foreign_key('calls_id_clients_contact_fkey', 'calls', 'contacts', ['id_clients_contact'], ['id'])
    # ### end Alembic commands ###
