"""empty message

Revision ID: 66668d429d11
Revises: 
Create Date: 2021-04-14 16:48:09.419059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66668d429d11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_name', 'subversion_id')
    op.create_foreign_key(None, 'subversion', 'org_name', ['org_name'], ['id'])
    op.drop_constraint('token_worker_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'worker', ['worker_id'], ['id'])
    op.drop_constraint('worker_login_id_org_name_key', 'worker', type_='unique')
    op.drop_constraint('worker_conf_worker_id_key', 'worker_conf', type_='unique')
    op.drop_constraint('worker_conf_worker_id_fkey', 'worker_conf', type_='foreignkey')
    op.create_foreign_key(None, 'worker_conf', 'worker', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_conf', type_='foreignkey')
    op.create_foreign_key('worker_conf_worker_id_fkey', 'worker_conf', 'worker', ['worker_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('worker_conf_worker_id_key', 'worker_conf', ['worker_id'])
    op.create_unique_constraint('worker_login_id_org_name_key', 'worker', ['login', 'id_org_name'])
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_worker_id_fkey', 'token', 'worker', ['worker_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'subversion', type_='foreignkey')
    op.add_column('org_name', sa.Column('subversion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
