"""empty message

Revision ID: 6995e7f884d4
Revises: d2c59fd1a590
Create Date: 2021-04-16 09:44:39.125200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6995e7f884d4'
down_revision = 'd2c59fd1a590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_pc', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients_pc', 'name')
    # ### end Alembic commands ###
