"""empty message

Revision ID: 7f355c0281d1
Revises: 053cc8402cde
Create Date: 2021-04-20 11:49:58.086919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f355c0281d1'
down_revision = '053cc8402cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('reason_calls', sa.Text(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_clients_contact', sa.Integer(), nullable=True),
    sa.Column('call_ended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_clients_contact'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otherrequesttime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('completed_work', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requesttime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_request', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requesttime')
    op.drop_table('otherrequesttime')
    op.drop_table('calls')
    # ### end Alembic commands ###
