"""empty message

Revision ID: a8c60ac179df
Revises: 9e3fc8df37d1
Create Date: 2021-04-23 14:11:49.150136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c60ac179df'
down_revision = '9e3fc8df37d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_in_the_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otherrequesttime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('completed_work', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_clients', sa.Integer(), nullable=True),
    sa.Column('id_worker_created', sa.Integer(), nullable=True),
    sa.Column('id_worker_responsible', sa.Integer(), nullable=True),
    sa.Column('id_contacts', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_clients'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_contacts'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['id_worker_created'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['id_worker_responsible'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['status'], ['request_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('id_workers', sa.Integer(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['id_workers'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_workers')
    op.drop_table('project_request')
    op.drop_table('otherrequesttime')
    op.drop_table('project_info')
    op.drop_table('project_doc')
    op.drop_table('change_in_the_project')
    # ### end Alembic commands ###
