"""empty message

Revision ID: afc64b1e2130
Revises: a8c60ac179df
Create Date: 2021-04-23 15:25:51.728973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc64b1e2130'
down_revision = 'a8c60ac179df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('id_orgname', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request_status', 'org_name', ['id_orgname'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_status', type_='foreignkey')
    op.drop_column('request_status', 'id_orgname')
    # ### end Alembic commands ###
