"""empty message

Revision ID: cb688fa9f4ef
Revises: 6995e7f884d4
Create Date: 2021-04-16 12:27:34.753109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb688fa9f4ef'
down_revision = '6995e7f884d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('support_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'support_time')
    # ### end Alembic commands ###
